

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DatabaseEntities
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class AsignarDBEntities : DbContext
{
    public AsignarDBEntities()
        : base("name=AsignarDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<DefectAttachment> DefectAttachments { get; set; }

    public virtual DbSet<DefectPriority> DefectPriorities { get; set; }

    public virtual DbSet<Defect> Defects { get; set; }

    public virtual DbSet<DefectStatus> DefectStatuses { get; set; }

    public virtual DbSet<Filter> Filters { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<ProjectsToUsersBinding> ProjectsToUsersBindings { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

}

}

