//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefectAttachment
    {
        public int AttachmentID { get; set; }
        public string AttachmentLink { get; set; }
        public Nullable<int> DefectID { get; set; }
    
        public virtual Defect Defect { get; set; }
    }
}
