//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filter
    {
        public int FilterID { get; set; }
        public string Search { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> AssigneeUserID { get; set; }
        public Nullable<int> DefectPriorityID { get; set; }
        public Nullable<int> DefectStatusID { get; set; }
    
        public virtual DefectPriority DefectPriority { get; set; }
        public virtual DefectStatus DefectStatus { get; set; }
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
